### ISSUE TITLE
Build fails with `LINK : fatal error LNK1104` due test executable is blocked by TestMate

### ISSUE THREAD

**Issue by HenkjanSmits** [matepek/vscode-catch2-test-adapter#235]
I use this extension in VS Code together with the CMmake Tools extension and Google Tests. When compiling projects using CMake the linker cannot access the output .exe files. This is because their handles are held by this extension, i think because of test discovery or something. As a consequence i either have to disable this extension during significant compilation work or re-start the compilation many times. There doesnt seem to be a config parameter that prevents this behaviour. 

  Steps:
    1. Compile significant project using CMake tools in VS Code with this extension and a pattern set that catches test projects e.g. 
                "pattern": "{build_vscode-Debug}*/**/*{test,Test,TEST}*",
    2. Observe linker trying to overwrite test .exe files but being prevented from doing so, stopping compilation.
    3. Disable the C++ TestMate extension, and run compilation again. Then there is no issue.

**Comment by matepek** [comment]
Hey,
This extension is only keeps open a handle if discovers, reads test list or execute tests.
I'm guessing in your case the second one is the situation. for that you can do a couple of things:

- you can split the executable to smaller ones. I think that would help a lot and there are other benefits of it too.
- you can enabling `discovery.testListCaching`. That might helps too.
- you can play with `discovery.runtimeLimit` but I don't think that would help actually.

Anyhow from the insufficient provided informations thats all I can do. Feel free to elaborate the issue with extensive informations for further assistance. ^^

**Comment by matepek** [comment]
Try this modified version: [vscode-catch2-test-adapter-3.6.7-dev.vsix.zip](https://github.com/matepek/vscode-catch2-test-adapter/files/5567718/vscode-catch2-test-adapter-3.6.7-dev.vsix.zip)
You can [install manually](https://www.google.com/search?q=vscode+install+package+manually).

**Comment by HenkjanSmits** [comment]
Great Ill try! I am currently running with the caching option for discovery you advised but I did see the problem again at least once.

The tests are already split over 100 exe files with just a few tests per file.

I guess I could send the logs from the extension but im not sure how useful that would be. Sending the project is not possible for confidentiality reasons and sending a small project might not show the problem because it happens "sporadically" (the linker and the extension need to be holding the same file at exactly the same moment) and is more prevalent on larger builds with lots of exes.

Best regards,

Maarten

________________________________

**Comment by matepek** [comment]
Well, for beginning it would be nice if you would fill [this](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
I don't even now your type :P

**Comment by HenkjanSmits** [comment]
Yes, sorry. I made an attempt at this probably there is some webform that can actually be filled but I just completed the text version:

- [X] The issue is about this extension and NOT about a fork.
- [X] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [X] The latest version of the extension was used.
- [X] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

When compiling the linker fails because it cannot write to the .exe file. The problem is gone when this
extension is deactivated. Linker failure messages are like:

[build] LINK : fatal error LNK1104: cannot open file '<name>.exe'

**To Reproduce**

Activate this extension and CMake Tools in VSCode. Make a settings file for this extension which catches
test patterns in the build directory. Then build a project using CMake Tools (1.5.2).

**Screenshots** (optional)
N/A

- Extension Version: v3.6.4
- VS Code Version: 1.5.1
- Catch2 / Google Test / DOCTest Version: 1.8.0
- OS Type and Version: Windows 10 Pro 10.19041 Build 19041.
- Using remote-ssh/docker/wsl?: No

**Regression bug?**
No, I dont think so I have had this bug since about 6 months, there is no reason for me to think this is a regression.



________________________________

**Comment by HenkjanSmits** [comment]
And here is a bug report for the modified version v3.6.7-dev. Problem remains. Note that i also turned on "testMate.cpp.discovery.testListCaching": true. I dont know exactly what testdiscovery involves but if the .exe's involved also depend on DLL's that need to load maybe time taken for test discovery is quite long and the file is held all that time? I think what would be great is just an option to turn test discovery off temporarily (e.g. next to the Enable Autorun and Disable Autorun options in the test panel?) without disabling and enabling the extension (that is a pain because you need to restart VS Code to do that).

- [ ] The issue is about this extension and NOT about a fork. -> i think the dev version you sent me is technically a fork 🙂.
- [X] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [X] The latest version of the extension was used.
- [X] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

When compiling the linker fails because it cannot write to the .exe file. The problem is gone when this
extension is deactivated. Linker failure messages are like:

[build] LINK : fatal error LNK1104: cannot open file '<name>.exe'

**To Reproduce**

Activate this extension and CMake Tools in VSCode. Make a settings file for this extension which catches
test patterns in the build directory. Set the extension option:

"testMate.cpp.discovery.testListCaching": true

Then build a project using CMake Tools (1.5.2).

**Screenshots** (optional)
N/A

- Extension Version: v3.6.7-dev
- VS Code Version: 1.5.1
- Catch2 / Google Test / DOCTest Version: 1.8.0
- OS Type and Version: Windows 10 Pro 10.19041 Build 19041.
- Using remote-ssh/docker/wsl?: No

**Regression bug?**
No, I dont think so I have had this bug since about 6 months, there is no reason for me to think this is a regression.



________________________________

**Comment by matepek** [comment]
> Problem remains.

Well thats not a good sign.

I have another idea and since you are using CMake it's fairly to work with it. 
**Do you have control over your source?** 
We have to do some modification on the build system. Nothing serious thought.

**Comment by matepek** [comment]
And I would need your **full** log. (I'm saying full because in a lot of cases people just sending me what they think its relevant. Sometimes it's ok but mostly annoying. Well you are a programmer, you can imagine.) 
It contains diagnostic informations which will help me a lot. Check this for [how to](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Comment by matepek** [comment]
Also, try this experimental build: [vscode-catch2-test-adapter-3.6.8-dev.vsix.zip](https://github.com/matepek/vscode-catch2-test-adapter/files/5577312/vscode-catch2-test-adapter-3.6.8-dev.vsix.zip)

**Comment by HenkjanSmits** [comment]
Dear Mate Pek,

Just a small update: im trying this build at the moment and will get the logs, please allow some time because I integrate this in my normal workflow and the problem is not 100% reproducible so I need some time to be sure what the effect is.

Best regards,
Maarten Nauta

________________________________

**Comment by HenkjanSmits** [comment]
Dear Mate Pek,

OK it seems your recent change below worked, in the mean time I have also updated to 3.6.11 which also seems to work (probably it has the fix incorporated?). But its only from a week of use so maybe I missed something.

Thanks a lot for fixing this i could not find a donate button but if there is im happy to donate something to development.

Best regards,

Maarten Nauta



________________________________

**Comment by HenkjanSmits** [comment]
Dear Mate Pek,

OK with 3.6.11 bug is still there. Bug report updated to reflect that version change. Logfile attached, also contains the cmake output with the linker error.

With the custom 3.6.8_dev version you sent I didnt encounter this but i only used that for a week after which i updated to 3.6.11. I did notice on that version 3.6.8 that test access in the testpanel was very slow. Should i go back to testing that version?

Best regards,

Maarten

- [X] The issue is about this extension and NOT about a fork.
- [X] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [X] The latest version of the extension was used.
- [X] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

When compiling the linker fails because it cannot write to the .exe file. The problem is gone when this
extension is deactivated. Linker failure messages are like:

[build] LINK : fatal error LNK1104: cannot open file '<name>.exe'

**To Reproduce**

Activate this extension and CMake Tools in VSCode. Make a settings file for this extension which catches
test patterns in the build directory. Then build a project using CMake Tools (1.5.2).

**Screenshots** (optional)
N/A

- Extension Version: v3.6.11
- VS Code Version: 1.51.1
- Catch2 / Google Test / DOCTest Version: 1.8.0
- OS Type and Version: Windows 10 Pro 10.19041 Build 19041.
- Using remote-ssh/docker/wsl?: No

**Regression bug?**
No, I dont think so I have had this bug since about 6 months, there is no reason for me to think this is a regression.



________________________________

**Comment by matepek** [comment]
The *3.6.8_dev* version is special. Tell me more about the "test access in the testpanel was very slow". I have to understand the effects of that feature before I release it.

**Comment by matepek** [comment]
Until further investigation/information I'm closing this issue.
